import keyMirror from 'keymirror';

export default keyMirror({
  API_CALL: null,

  AUTHENTICATION_DATA_RESET: null,
  AUTHENTICATION_LOGIN_FAILURE: null,
  AUTHENTICATION_LOGIN_REQUEST: null,
  AUTHENTICATION_LOGIN_SUCCESS: null,
  AUTHENTICATION_LOGIN_TOKEN_FAILURE: null,
  AUTHENTICATION_LOGIN_TOKEN_REQUEST: null,
  AUTHENTICATION_LOGIN_TOKEN_SUCCESS: null,
  AUTHENTICATION_REGISTER_FAILURE: null,
  AUTHENTICATION_REGISTER_REQUEST: null,
  AUTHENTICATION_REGISTER_SUCCESS: null,
  CITY_GET_FAILURE: null,
  CITY_GET_REQUEST: null,
  CITY_GET_SUCCESS: null,
  SERVICE_GET_FAILURE: null,
  SERVICE_GET_REQUEST: null,
  SERVICE_GET_SUCCESS: null,
});
