export default {
  1: 'Zagrebačka',
  2: 'Krapinsko-Zagorska',
  3: 'Sisačko-moslovačka',
  4: 'Karlovačka',
  5: 'Varaždniska',
  6: 'Koprivničko-Križevačka',
  7: 'Bjelovarsko-Bilogorska',
  8: 'Primorsko-Goranska',
  9: 'Ličko-Senjska',
  10: 'Virovitičko-Podravska',
  11: 'Poževsko-Slavonska',
  12: 'Brodsko-Posavska',
  13: 'Zadarska',
  14: 'Osječko-Baranjska',
  15: 'Šibensko-Kninska',
  16: 'Vukovarsko-Srijemska',
  17: 'Splitsko-Dalmatinska',
  18: 'Istarska',
  19: 'Dubrovačko-Neretvanska',
  20: 'Medimurska',
  21: 'Grad Zagreb',
};
